### ISSUE TITLE
connection to the DB should be taken from Model not ActiveRecord

### ISSUE THREAD

**Issue by dzidas** [paolodona/import_with_load_data_in_file#1]
Hi Paolo, 

I found your plugin very helpful:) I've noticed one issue you maybe would like to consider.
In my application I've got few models which connects to another database. While trying your plugin with those Models data were stored in wrong database. I needed to change a bit your plugin in order to work in the way I would like to work,

So, I've changed this line:
ActiveRecord::Base.connection.execute(sql)
to:
self.connection.execute(sql)

Let me know what are you thoughts.

Thanks, 
Rafal

**Comment by paolodona** [comment]
Rafal, thank you for your message.
I think you're right. 
I'm not actively working on the plugin at the moment, but feel free to clone the repo and apply your own changes. I will add a line on the wiki pointing to your fork!

Paolo
